categories = ["String"]
difficulty = "Medium"
entrypoints = ["zig_zag_convert"]
id = 6
link = "https://leetcode.com/problems/zigzag-conversion/description/"
slug = "zig-zag-conversion"
title = "ZigZag Conversion"

[progress]
attempts = 53
best_bytes = 1298152
best_time_ns = 8127669
first_solved_at = "2026-08-30"
notes = ""
solved_at = "2026-08-30"
status = "solved"

[[runs]]
at = "2026-08-27T11:27:19"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:27:55"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:28:24"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:32:10"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:32:48"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:33:43"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:33:58"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:35:26"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:36:08"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:50:43"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:52:19"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:52:53"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:53:48"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:55:04"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:55:52"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T11:59:55"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T12:01:10"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T12:01:33"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T12:07:11"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T12:09:30"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T12:15:10"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T12:22:17"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T12:22:53"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-27T12:23:14"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T10:41:46"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T10:48:12"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T10:52:11"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T10:53:08"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T10:55:14"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T10:56:44"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T11:00:06"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T11:00:41"
bytes = 0
mode = "solution"
n_error = 3
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:09:50"
bytes = 0
mode = "solution"
n_error = 1
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:13:18"
bytes = 0
mode = "solution"
n_error = 1
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:15:17"
bytes = 0
mode = "solution"
n_error = 1
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:16:52"
bytes = 0
mode = "solution"
n_error = 1
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:17:32"
bytes = 0
mode = "solution"
n_error = 1
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:21:29"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:22:10"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:24:15"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:24:43"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:25:44"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:26:25"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:26:41"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:27:42"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:35:57"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:37:14"
bytes = 0
mode = "solution"
n_error = 1
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:37:35"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:40:07"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:45:49"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:46:34"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 1
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-30T17:49:41"
bytes = 1298152
mode = "solution"
n_error = 0
n_fail = 0
n_pass = 1
passed = true
time_ns = 8127669
[[runs]]
at = "2026-08-30T17:52:13"
bytes = 0
mode = "solution"
n_error = 1
n_fail = 1
n_pass = 1
passed = false
time_ns = 0

[source]
author = "Tian Jun"
date = "2020-10-31"
repo = "https://github.com/JuliaCN/LeetCode.jl"
