categories = ["Array", "Two Pointers"]
difficulty = "Medium"
entrypoints = ["three_sum!", "three_sum"]
id = 15
link = "https://leetcode.com/problems/3sum/description/"
runs = []
slug = "3sum"
title = "3Sum"

[progress]
attempts = 0
best_bytes = 0
best_time_ns = 0
first_solved_at = ""
notes = ""
solved_at = ""
status = "todo"

[source]
author = "zhwang"
date = "2022-03-15"
repo = "https://github.com/JuliaCN/LeetCode.jl"
