categories = ["Array", "Binary Search", "Divide and Conquer"]
difficulty = "Hard"
entrypoints = ["find_median_sorted_arrays", "nth"]
id = 4
link = "https://leetcode.com/problems/median-of-two-sorted-arrays/description/"
slug = "median-of-two-sorted-arrays"
title = "Median of Two Sorted Arrays"

[progress]
attempts = 19
best_bytes = 2428008
best_time_ns = 43521005
first_solved_at = "2026-08-23"
notes = ""
solved_at = "2026-08-23"
status = "solved"

[[runs]]
at = "2026-08-23T20:47:06"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T20:47:40"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T20:59:10"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:02:50"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:04:34"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:07:42"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:08:34"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:09:30"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:15:52"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:16:13"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:19:31"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:20:11"
bytes = 0
mode = "solution"
n_error = 1
n_fail = 0
n_pass = 41
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:21:11"
bytes = 2428008
mode = "solution"
n_error = 0
n_fail = 0
n_pass = 42
passed = true
time_ns = 43521005
[[runs]]
at = "2026-08-23T21:25:51"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:27:04"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:27:42"
bytes = 0
mode = "solution"
n_error = 42
n_fail = 0
n_pass = 0
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:28:12"
bytes = 0
mode = "solution"
n_error = 0
n_fail = 35
n_pass = 7
passed = false
time_ns = 0
[[runs]]
at = "2026-08-23T21:28:42"
bytes = 2428008
mode = "solution"
n_error = 0
n_fail = 0
n_pass = 42
passed = true
time_ns = 47042437
[[runs]]
at = "2026-08-23T21:29:36"
bytes = 2428008
mode = "solution"
n_error = 0
n_fail = 0
n_pass = 42
passed = true
time_ns = 43825147

[source]
author = "Tian Jun"
date = "2020-10-31"
repo = "https://github.com/JuliaCN/LeetCode.jl"
